package com.sk.menu.model;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_menu.id
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_menu.treeId
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    private Integer treeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_menu.pid
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_menu.name
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_menu.rel
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    private String rel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_menu.kind
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    private Integer kind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_menu.id
     *
     * @return the value of bg_menu.id
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_menu.id
     *
     * @param id the value for bg_menu.id
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_menu.treeId
     *
     * @return the value of bg_menu.treeId
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public Integer getTreeid() {
        return treeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_menu.treeId
     *
     * @param treeid the value for bg_menu.treeId
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public void setTreeid(Integer treeid) {
        this.treeid = treeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_menu.pid
     *
     * @return the value of bg_menu.pid
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_menu.pid
     *
     * @param pid the value for bg_menu.pid
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_menu.name
     *
     * @return the value of bg_menu.name
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_menu.name
     *
     * @param name the value for bg_menu.name
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_menu.rel
     *
     * @return the value of bg_menu.rel
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public String getRel() {
        return rel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_menu.rel
     *
     * @param rel the value for bg_menu.rel
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public void setRel(String rel) {
        this.rel = rel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_menu.kind
     *
     * @return the value of bg_menu.kind
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public Integer getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_menu.kind
     *
     * @param kind the value for bg_menu.kind
     *
     * @mbggenerated Thu Jun 30 21:53:46 CST 2016
     */
    public void setKind(Integer kind) {
        this.kind = kind;
    }
}