package com.sk.menu.model;

import java.util.Date;

import com.sk.util.DateUtil;

public class MyProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_my_project.id
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_my_project.name
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_my_project.office_start
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    private Date officeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_my_project.office_end
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    private Date officeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_my_project.creator
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    private Integer creator;
   
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_my_project.create_time
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_my_project.id
     *
     * @return the value of bg_my_project.id
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    private Integer statusId;
    //创建者昵称
    private String creatorStr;
    //项目状态str
    private String statusStr;
    
    public String getStatusStr() {
		return statusStr;
	}

	public void setStatusStr(String statusStr) {
		this.statusStr = statusStr;
	}

	public String getCreatorStr() {
		return creatorStr;
	}

	public void setCreatorStr(String creatorStr) {
		this.creatorStr = creatorStr;
	}

	public Integer getId() {
        return id;
    }
	public Integer getStatusId() {
        return statusId;
	}
	
	public void setStatusId(Integer statusId) {
	    this.statusId = statusId;
	}
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_my_project.id
     *
     * @param id the value for bg_my_project.id
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_my_project.name
     *
     * @return the value of bg_my_project.name
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_my_project.name
     *
     * @param name the value for bg_my_project.name
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_my_project.office_start
     *
     * @return the value of bg_my_project.office_start
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public String getOfficeStart() {
        return DateUtil.fomartDateToStr(officeStart, DateUtil.SHORT_PATT);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_my_project.office_start
     *
     * @param officeStart the value for bg_my_project.office_start
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public void setOfficeStart(Date officeStart) {
        this.officeStart = officeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_my_project.office_end
     *
     * @return the value of bg_my_project.office_end
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public String getOfficeEnd() {
        return DateUtil.fomartDateToStr(officeEnd, DateUtil.SHORT_PATT);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_my_project.office_end
     *
     * @param officeEnd the value for bg_my_project.office_end
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public void setOfficeEnd(Date officeEnd) {
        this.officeEnd = officeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_my_project.creator
     *
     * @return the value of bg_my_project.creator
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_my_project.creator
     *
     * @param creator the value for bg_my_project.creator
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_my_project.create_time
     *
     * @return the value of bg_my_project.create_time
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public String getCreateTime() {
        return DateUtil.fomartDateToStr(createTime, DateUtil.SHORT_PATT);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_my_project.create_time
     *
     * @param createTime the value for bg_my_project.create_time
     *
     * @mbggenerated Thu Jul 14 19:27:01 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}