package com.sk.menu.model;

public class UserKind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_user_kind.id
     *
     * @mbggenerated Thu Jun 30 21:52:50 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_user_kind.name
     *
     * @mbggenerated Thu Jun 30 21:52:50 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_user_kind.id
     *
     * @return the value of bg_user_kind.id
     *
     * @mbggenerated Thu Jun 30 21:52:50 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_user_kind.id
     *
     * @param id the value for bg_user_kind.id
     *
     * @mbggenerated Thu Jun 30 21:52:50 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_user_kind.name
     *
     * @return the value of bg_user_kind.name
     *
     * @mbggenerated Thu Jun 30 21:52:50 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_user_kind.name
     *
     * @param name the value for bg_user_kind.name
     *
     * @mbggenerated Thu Jun 30 21:52:50 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}